Add files via upload
slight change to code, now retweets another random colour and keeps going till it crashes on selecting the same colour again. also get the following every so often:      
arp_detailed = struct.unpack('2s2s1s1s2s6s4s6s4s', arp_header)
struct.error: unpack requires a string argument of length 28